### ISSUE TITLE
Can you explain more about the `awk` line?

### ISSUE THREAD

**Issue by shuaishuai** [aterreno/activemq-dockerfile#3]
That saves my life. Thanks a lot! However, I still want to know why.

**Comment by aterreno** [comment]
Sure, that line basically configures the actimemq to use stomp: there's a activemq.xml.orig which becomes activemq.xml, if you don't need stomp or need a different config for the transportConnector then you'll have to change that line. Check the section http://activemq.apache.org/stomp.html 'enabling stomp over nio' 

Time has passed.. I don't use activemq any longer, I hope it helps!
